### ISSUE TITLE
Does it require essl etimetracklite web to be installed?

### ISSUE THREAD

**Issue by xXWarMachineRoXx** [rtdany10/etimetracklite#1]
- I don't think we can send the soap request to the desktop app

# Environment

- Windows 11
- etimetracklite 11.10 (Desktop)
- Device: essl k30

**Comment by rtdany10** [comment]
Hi @xXWarMachineRoXx 
Yes eTimeTrackLite Web is required as the desktop application doesn't support API calls.

<hr>

P.S I have updated the readme, sorry for the confusion.

**Comment by xXWarMachineRoXx** [comment]
Hey @rtdany10 , I tried getting info using tcp and the software dlls, is that possible and , can you help me out with that?

**Comment by rtdany10** [comment]
If you have access to the physical machine from your system, you can use this library to fetch the logs: https://github.com/fananimi/pyzk
@xXWarMachineRoXx

**Comment by xXWarMachineRoXx** [comment]
@rtdany10 , thanks man 

I figured that out shortly after and successfully connected and got logs

But I could not send the new logs created from my face recognition device back to the zk device

I see that you were a contributor to that repo ( pyzk)

**Comment by rtdany10** [comment]
> But I could not send the new logs created from my face recognition device back to the zk device

I did not understand, can you elaborate? What is the purpose of sending back to the device?

**Comment by xXWarMachineRoXx** [comment]
@rtdany10 , I mean. I am integrating a new app that also creates attendance logs and I wanted to merge them
So, I was thinking how can I send newly created logs back to the device. ( i am avoiding downloading to etimetracklite and chaning the sql/msaccess database)

# Why ?
well I am trying to integrate a face recognition arduino - door access - to a HR app called [kredily](https://kredily.com/) . But I do not want to keep a server that downloads logs in SQL/MS Access and sends to the HR app ( kredily). So what if I can make the device push to kredily directly? ( ADMS / IP mode, cloud sever settings , anything that might work _ 

- my device is a essl identix k30

**Comment by rtdany10** [comment]
@xXWarMachineRoXx why not push the logs that you have on arduino directly to Kredily? Also push the logs from the biometric machine to your HRMS.

<hr>

Edit: https://github.com/frappe/biometric-attendance-sync-tool/blob/master/erpnext_sync.py is a great script that you can refer to. It fetches data from the machine and pushes to ERPNext.

**Comment by xXWarMachineRoXx** [comment]
I would love to, but kredily ,afaik, doesn't provide an api or something that would help. i contacted them and they would get back to me shortly.

**Comment by xXWarMachineRoXx** [comment]
> @xXWarMachineRoXx why not push the logs that you have on arduino directly to Kredily? Also push the logs from the biometric machine to your HRMS.
> 
> Edit: https://github.com/frappe/biometric-attendance-sync-tool/blob/master/erpnext_sync.py is a great script that you can refer to. It fetches data from the machine and pushes to ERPNext.

I actually found a way, the way you can do that is that there is a manual csv upload button on Kredily. I can write a selenium script that uploads a csv periodically with the new logs 😄  ( this method can be used with any hrms software cuz I imagine everyone of them would have a manual upload, but the way to do it would be different)

**Comment by rtdany10** [comment]
> I actually found a way, the way you can do that is that there is a manual csv upload button on Kredily. 

> I can write a selenium script that uploads a csv periodically with the new logs 😄

Why selenium? Pretty sure an api endpoint is called when you upload the csv file. Keep an eye out on your network tab on browser. Call the same API with required parameters and cookies or auth tokens(?)

**Comment by xXWarMachineRoXx** [comment]
> > I actually found a way, the way you can do that is that there is a manual csv upload button on Kredily.
> 
> > I can write a selenium script that uploads a csv periodically with the new logs 😄
> 
> Why selenium? Pretty sure an api endpoint is called when you upload the csv file. Keep an eye out on your network tab on browser. Call the same API with required parameters and cookies or auth tokens(?)

Well, that is an interesting idea, would really ease my workflow ( It's is really tedious to get every className/Selector etc in selenium) 

Would lookout on that! I really appreciate your responsiveness to this thread! Thank you kind stranger! 😇🫡

**Comment by xXWarMachineRoXx** [comment]
[And here it is](https://github.com/xXWarMachineRoXx/doorito/tree/streamlit)

thx , it needs a lot of work tho.

**Comment by rtdany10** [comment]
Congratulations! :partying_face: :smile:
